const artists = {
    abstract: [
        { name: 'Wassily Kandinsky', url: require('../../public/images/artists/abstractionism/kandinsky.jpeg') },
        { name: 'Piet Mondrian', url: require('../../public/images/artists/abstractionism/mondrian.jpeg') },
        { name: 'Jackson Pollock', url: require('../../public/images/artists/abstractionism/pollock.jpeg') },
        { name: 'Mark Rothko', url: require('../../public/images/artists/abstractionism/rothko.jpeg') },
        { name: 'Gerhard Richter', url: require('../../public/images/artists/abstractionism/richter.jpeg') },
        { name: 'Robert Motherwell', url: require('../../public/images/artists/abstractionism/motherwell.jpeg') },
        { name: 'Hilma af Klint', url: require('../../public/images/artists/abstractionism/klint.jpeg') },
        { name: 'Kazimir Malevich', url: require('../../public/images/artists/abstractionism/malevich.jpeg') },
    ],
    classic: [
        { name: 'Nicolas Poussin', url: require('../../public/images/artists/classicism/poussin.jpeg') },
        { name: 'Lauren de La Hyre', url: require('../../public/images/artists/classicism/hyre.jpeg') },
        { name: 'Charles Le Brun', url: require('../../public/images/artists/classicism/brun.jpeg') },
        { name: 'Louis Le Nain', url: require('../../public/images/artists/classicism/nain.jpeg') },
        { name: 'Jean Baptiste Chardin', url: require('../../public/images/artists/classicism/chardin.jpeg') },
        { name: 'Jacques-Louis David', url: require('../../public/images/artists/classicism/david.jpeg') },
        { name: 'Jean-Auguste-Dominique Ingres', url: require('../../public/images/artists/classicism/ingres.jpeg') },
        { name: 'Pompeo Batoni', url: require('../../public/images/artists/classicism/batoni.jpeg') },
    ],
    cubism: [
        { name: 'Pablo Picasso', url: require('../../public/images/artists/cubism/picasso.jpeg') },
        { name: 'Georges Braque', url: require('../../public/images/artists/cubism/braque.jpeg') },
        { name: 'Marc Chagall', url: require('../../public/images/artists/cubism/chagall.jpeg') },
        { name: 'Jean Metzinger', url: require('../../public/images/artists/cubism/metzinger.jpeg') },
        { name: 'Juan Gris', url: require('../../public/images/artists/cubism/gris.jpeg') },
        { name: 'David Bomberg', url: require('../../public/images/artists/cubism/bomberg.jpeg') },
        { name: 'Fernand Léger', url: require('../../public/images/artists/cubism/léger.jpeg') },
        { name: 'Emily Carr', url: require('../../public/images/artists/cubism/carr.jpeg') },
    ],
    express: [
        { name: 'Edvard Munch', url: require('../../public/images/artists/expressionism/munch.jpeg') },
        { name: 'Vincent van Gogh', url: require('../../public/images/artists/expressionism/gogh.jpeg') },
        { name: 'Ernst Ludwig Kirchner', url: require('../../public/images/artists/expressionism/kirchner.jpeg') },
        { name: 'Wolfgang Neumann', url: require('../../public/images/artists/expressionism/neumann.jpeg') },
        { name: 'Egon Schiele', url: require('../../public/images/artists/expressionism/schiele.jpeg') },
        { name: 'Franz Marc', url: require('../../public/images/artists/expressionism/marc.jpeg') },
        { name: 'Amedeo Modigliani', url: require('../../public/images/artists/expressionism/modigliani.jpeg') },
        { name: 'August Macke', url: require('../../public/images/artists/expressionism/macke.jpeg') },
    ],
    impress: [
        { name: 'Édouard Manet', url: require('../../public/images/artists/impressionism/manet.jpeg') },
        { name: 'Claude Monet', url: require('../../public/images/artists/impressionism/monet.jpeg') },
        { name: 'Edgar Degas', url: require('../../public/images/artists/impressionism/degas.jpeg') },
        { name: 'Camille Pissarro', url: require('../../public/images/artists/impressionism/pissarro.jpeg') },
        { name: 'Pierre-Auguste Renoir', url: require('../../public/images/artists/impressionism/renoir.jpeg') },
        { name: 'Mary Cassatt', url: require('../../public/images/artists/impressionism/cassatt.jpeg') },
        { name: 'Berthe Marie Pauline Morisot', url: require('../../public/images/artists/impressionism/morisot.jpeg') },
        { name: 'Gustave Caillebotte', url: require('../../public/images/artists/impressionism/caillebotte.jpeg') },
    ],
    minimal: [
        { name: 'Frank Stella', url: require('../../public/images/artists/minimalism/stella.jpeg') },
        { name: 'Agnes Martin', url: require('../../public/images/artists/minimalism/martin.jpeg') },
        { name: 'Sol LeWitt', url: require('../../public/images/artists/minimalism/leWitt.jpeg') },
        { name: 'Yayoi Kusama', url: require('../../public/images/artists/minimalism/kusama.jpeg') },
        { name: 'Ellsworth Kelly', url: require('../../public/images/artists/minimalism/kelly.jpeg') },
        { name: 'Brent Hallard', url: require('../../public/images/artists/minimalism/hallard.jpeg') },
        { name: 'Mary Obering', url: require('../../public/images/artists/minimalism/obering.jpeg') },
        { name: 'Robert Moskowitz', url: require('../../public/images/artists/minimalism/moskowitz.jpeg') },
    ],
    popart: [
        { name: 'Andy Warhol', url: require('../../public/images/artists/popart/warhol.jpeg') },
        { name: 'Roy Lichtenstein', url: require('../../public/images/artists/popart/lichtenstein.jpeg') },
        { name: 'Jasper Johns', url: require('../../public/images/artists/popart/johns.jpeg') },
        { name: 'Robert Rauschenberg', url: require('../../public/images/artists/popart/rauschenberg.jpeg') },
        { name: 'Tom Wesselmann', url: require('../../public/images/artists/popart/wesselmann.jpeg') },
        { name: 'Keith Haring', url: require('../../public/images/artists/popart/haring.jpeg') },
        { name: 'David Diao', url: require('../../public/images/artists/popart/diao.jpeg') },
        { name: 'David Hockney', url: require('../../public/images/artists/popart/hockney.jpeg') },
    ],
    realism: [
        { name: 'Gustave Courbet', url: require('../../public/images/artists/realism/courbet.jpeg') },
        { name: 'Ilya Repin', url: require('../../public/images/artists/realism/repin.jpeg') },
        { name: 'Jean-Francois Millet', url: require('../../public/images/artists/realism/millet.jpeg') },
        { name: 'Rosa Bonheur', url: require('../../public/images/artists/realism/bonheur.jpeg') },
        { name: 'Winslow Homer', url: require('../../public/images/artists/realism/homer.jpeg') },
        { name: 'Thomas Eakins', url: require('../../public/images/artists/realism/eakins.jpeg') },
        { name: 'Andrew Wyeth', url: require('../../public/images/artists/realism/wyeth.jpeg') },
        { name: 'Vasily Surikov', url: require('../../public/images/artists/realism/surikov.jpeg') },
    ],
    renaiss: [
        { name: 'Leonardo da Vinci', url: require('../../public/images/artists/renaissance/vinci.jpeg') },
        { name: 'Raphael', url: require('../../public/images/artists/renaissance/raphael.jpeg') },
        { name: 'Sandro Botticelli', url: require('../../public/images/artists/renaissance/botticelli.jpeg') },
        { name: 'Albrecht Dürer', url: require('../../public/images/artists/renaissance/duerer.jpeg') },
        { name: 'Michelangelo Caravaggio', url: require('../../public/images/artists/renaissance/caravaggio.jpeg') },
        { name: 'Pieter Bruegel der Ältere', url: require('../../public/images/artists/renaissance/aeltere.jpeg') },
        { name: 'Tizian', url: require('../../public/images/artists/renaissance/tizian.jpeg') },
        { name: 'Michelangelo', url: require('../../public/images/artists/renaissance/michelangelo.jpeg') },
    ],
    surreal: [
        { name: 'Salvador Dali', url: require('../../public/images/artists/surrealism/dali.jpeg') },
        { name: 'Rene Magritte', url: require('../../public/images/artists/surrealism/magritte.jpeg') },
        { name: 'Max Ernst', url: require('../../public/images/artists/surrealism/ernst.jpeg') },
        { name: 'Dorothea Tanning', url: require('../../public/images/artists/surrealism/tanning.jpeg') },
        { name: 'Leonora Carrington', url: require('../../public/images/artists/surrealism/carrington.jpeg') },
        { name: 'Joan Miro', url: require('../../public/images/artists/surrealism/miro.jpeg') },
        { name: 'Frida Kahlo', url: require('../../public/images/artists/surrealism/kahlo.jpeg') },
        { name: 'Zdzisław Beksiński', url: require('../../public/images/artists/surrealism/beksinski.jpeg') },
    ]
};

export default artists;